
version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mood-tunes-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URL=${MONGODB_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mood-tunes-network
    env_file:
      - .env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mood-tunes-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - VITE_SERVER_URL=http://server:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - mood-tunes-network
    env_file:
    - .env

networks:
  mood-tunes-network:
    driver: bridge